# Generated by Django 4.2.7 on 2023-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50, verbose_name='نام گره')),
                ('node_port', models.CharField(max_length=50, verbose_name='شماره پورت')),
                ('node_url', models.URLField(verbose_name='آدرس گره')),
                ('node_inventory', models.FloatField(default=0.0, verbose_name='موجودی حساب گره')),
                ('node_join_to_network', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ملحق شدن گره به شبکه')),
            ],
            options={
                'verbose_name': 'گره',
                'verbose_name_plural': 'گره ها',
            },
        ),
    ]
