# Generated by Django 4.2.7 on 2023-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50, unique=True, verbose_name='نام گره')),
                ('node_port', models.CharField(max_length=50, unique=True, verbose_name='شماره پورت')),
                ('node_url', models.URLField(unique=True, verbose_name='آدرس گره')),
                ('node_inventory', models.FloatField(default=0.0, verbose_name='موجودی حساب گره')),
                ('node_join_to_network', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ملحق شدن گره به شبکه')),
                ('node_address', models.CharField(blank=True, editable=False, max_length=500, null=True, unique=True, verbose_name='آدرس گره')),
                ('is_disable', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'گره',
                'verbose_name_plural': 'گره ها',
            },
        ),
    ]
