# Generated by Django 4.2.7 on 2024-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='mined_block_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بلوک های استخراج کرده'),
        ),
    ]
