# Generated by Django 4.2.7 on 2023-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemodel',
            name='node_inventory',
            field=models.FloatField(default=0.0, editable=False, verbose_name='موجودی حساب گره'),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='node_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام گره'),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='node_port',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره پورت'),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='node_url',
            field=models.URLField(unique=True, verbose_name='آدرس گره'),
        ),
    ]
