# Generated by Django 4.2.7 on 2023-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0002_alter_nodemodel_node_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='node_address',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, unique=True, verbose_name='آدرس گره'),
        ),
    ]
