# Generated by Django 4.2.7 on 2023-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0003_nodemodel_node_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemodel',
            name='node_inventory',
            field=models.FloatField(default=0.0, verbose_name='موجودی حساب گره'),
        ),
    ]
