# Generated by Django 4.2.7 on 2023-12-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0005_nodemodel_is_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemodel',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
