# Generated by Django 4.2.7 on 2023-12-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_module', '0006_alter_nodemodel_is_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodemodel',
            name='is_disable',
        ),
    ]
