# Generated by Django 4.2.7 on 2023-12-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_module', '0003_remove_propertymodel_property_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_owner_address', models.CharField(max_length=500, verbose_name='آدرس مالک توکن')),
                ('token_id', models.CharField(max_length=500, unique=True, verbose_name='شماره توکن ملک')),
                ('token_created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد توکن')),
                ('property_of_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_of_token', to='property_module.propertymodel', verbose_name='ملک مربوط به توکن')),
            ],
            options={
                'verbose_name': 'توکن',
                'verbose_name_plural': 'توکن ها',
            },
        ),
    ]
