# Generated by Django 4.2.7 on 2023-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=250, verbose_name='نام قرارداد هوشمند')),
                ('contract_address', models.CharField(editable=False, max_length=2000, verbose_name='آدرس قرارداد هوشمند')),
                ('contract_inventory', models.FloatField(default=0.0, verbose_name='موجودی قرارداد هوشمند')),
                ('nonce', models.IntegerField(default=0, verbose_name='تعداد دفعات فراخوانی')),
            ],
            options={
                'verbose_name': 'قرارداد هوشمند',
                'verbose_name_plural': 'قراردادهای هوشمند',
            },
        ),
    ]
