# Generated by Django 4.2.7 on 2023-12-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_module', '0002_smartcontractmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytokenmodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شده/نشده'),
        ),
    ]
