# Generated by Django 4.2.7 on 2023-12-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_module', '0003_remove_propertymodel_property_status_and_more'),
        ('token_module', '0003_propertytokenmodel_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytokenmodel',
            name='property_of_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_of_token', to='property_module.propertymodel', verbose_name='ملک مربوط به توکن'),
        ),
        migrations.AlterField(
            model_name='propertytokenmodel',
            name='property_owner_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس مالک توکن'),
        ),
    ]
