# Generated by Django 4.2.7 on 2023-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_module', '0004_alter_propertytokenmodel_property_of_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytokenmodel',
            name='token_information',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات مربوط به توکن'),
        ),
    ]
