# Generated by Django 4.2.7 on 2024-01-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_request_from', models.CharField(blank=True, max_length=500, null=True, verbose_name='درخواست از')),
                ('buy_request_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='درخواست به')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='token_module.propertytokenmodel', verbose_name='شماره توکن')),
            ],
        ),
        migrations.CreateModel(
            name='buyRequestStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در انتظار پذیرش')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده')),
                ('is_not_accepted', models.BooleanField(default=False, verbose_name='پذیرفته نشده')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='buy_and_sell_module.buyrequestmodel', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'وضعیت درخواست خرید',
                'verbose_name_plural': 'وضعیت درخواست های خرید',
            },
        ),
    ]
