# Generated by Django 4.2.7 on 2024-01-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_rejectBuyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_reject_status', models.BooleanField(default=False, verbose_name='پذیرفته شده/نشده')),
                ('accept_reject_buy_request_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='پذیرش یا رد درخواست خرید توسط')),
                ('accept_reject_buy_request_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='پذیرش یا رد درخواست خرید به')),
                ('accepted_rejected_buy_request_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد پذیرش یا رد درخواست خرید ملک')),
                ('accepted_rejected_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_rejected_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن پذیرفته شده/نشده')),
            ],
            options={
                'verbose_name': 'پذیرش یا رد درخواست خرید',
                'verbose_name_plural': 'پذیرش یا رد درخواست های خرید',
            },
        ),
        migrations.CreateModel(
            name='buyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizing_buy_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن خرید توسط')),
                ('finalizing_buy_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن خرید به')),
                ('finalizing_buy_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان نهایی کردن خرید ملک')),
                ('accept_reject_buy_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_reject_buy_request', to='buy_and_sell_module.accept_rejectbuyrequestmodel', verbose_name='درخواست خرید پذیرفته شده/نشده')),
                ('buyed_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن خریداری شده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
            },
        ),
        migrations.CreateModel(
            name='buyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_request_from', models.CharField(blank=True, max_length=500, null=True, verbose_name='درخواست از')),
                ('buy_request_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='درخواست به')),
                ('buy_request_created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد درخواست خرید ملک')),
                ('buy_request_prepayment', models.FloatField(default=0, verbose_name='مقدار بیعانه پیشنهادی')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='token_module.propertytokenmodel', verbose_name='شماره توکن')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست های خرید',
            },
        ),
        migrations.CreateModel(
            name='sellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizing_sell_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن فروش توسط')),
                ('finalizing_sell_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن فروش به')),
                ('finalizing_sell_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان نهایی کردن فروش ملک')),
                ('sell_status', models.BooleanField(default=False, verbose_name='وضعیت فروش')),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='buy_and_sell_module.buymodel', verbose_name='خرید')),
                ('selled_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن فروخته شده')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='buyStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در انتظار فروش')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('finalized_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_buy', to='buy_and_sell_module.buymodel', verbose_name='خرید نهایی شده')),
            ],
            options={
                'verbose_name': 'وضعیت خرید',
                'verbose_name_plural': 'وضعیت خریدها',
            },
        ),
        migrations.CreateModel(
            name='buyRequestStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در انتظار پذیرش')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='رد شده')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='buy_and_sell_module.buyrequestmodel', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'وضعیت درخواست خرید',
                'verbose_name_plural': 'وضعیت درخواست های خرید',
            },
        ),
        migrations.AddField(
            model_name='accept_rejectbuyrequestmodel',
            name='buy_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_request', to='buy_and_sell_module.buyrequestmodel', verbose_name='درخواست خرید'),
        ),
    ]
