# Generated by Django 4.2.7 on 2024-01-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequestmodel',
            name='buy_request_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد درخواست خرید ملک'),
        ),
    ]
