# Generated by Django 4.2.7 on 2024-01-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0002_buyrequestmodel_buy_request_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequeststatusmodel',
            name='is_not_accepted',
        ),
        migrations.AddField(
            model_name='buyrequeststatusmodel',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='رد شده'),
        ),
    ]
