# Generated by Django 4.2.7 on 2024-01-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0003_remove_buyrequeststatusmodel_is_not_accepted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyrequestmodel',
            options={'verbose_name': 'درخواست خرید', 'verbose_name_plural': 'درخواست های خرید'},
        ),
    ]
