# Generated by Django 4.2.7 on 2024-01-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0004_alter_buyrequestmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequestmodel',
            name='buy_request_prepayment',
            field=models.FloatField(default=0, verbose_name='مقدار بیعانه پیشنهادی'),
        ),
    ]
