# Generated by Django 4.2.7 on 2024-01-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0005_buyrequestmodel_buy_request_prepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_rejectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده/نشده')),
                ('accept_reject_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان پذیرش یا رد درخواست')),
                ('buy_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_request', to='buy_and_sell_module.buyrequestmodel', verbose_name='درخواست خرید')),
            ],
            options={
                'verbose_name': 'درخواست پذیرفته شده/نشده',
                'verbose_name_plural': 'درخواست های پذیرفته شده/نشده',
            },
        ),
    ]
