# Generated by Django 4.2.7 on 2024-01-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0006_accept_rejectmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accept_rejectModel',
        ),
    ]
