# Generated by Django 4.2.7 on 2024-01-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0007_delete_accept_rejectmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequestmodel',
            name='buy_request_prepayment',
        ),
    ]
