# Generated by Django 4.2.7 on 2024-01-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell_module', '0008_remove_buyrequestmodel_buy_request_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequestmodel',
            name='buy_request_prepayment',
            field=models.FloatField(default=0, verbose_name='مقدار بیعانه پیشنهادی'),
        ),
    ]
