# Generated by Django 4.2.7 on 2024-01-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_module', '0001_initial'),
        ('buy_and_sell_module', '0009_buyrequestmodel_buy_request_prepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_rejectBuyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_reject_status', models.BooleanField(default=False, verbose_name='پذیرفته شده/نشده')),
                ('accept_reject_buy_request_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='پذیرش یا رد درخواست خرید توسط')),
                ('accept_reject_buy_request_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='پذیرش یا رد درخواست خرید به')),
                ('accepted_rejected_buy_request_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد پذیرش یا رد درخواست خرید ملک')),
                ('accepted_rejected_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_rejected_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن پذیرفته شده/نشده')),
                ('buy_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_request', to='buy_and_sell_module.buyrequestmodel', verbose_name='درخواست خرید')),
            ],
            options={
                'verbose_name': 'پذیرش یا رد درخواست خرید',
                'verbose_name_plural': 'پذیرش یا رد درخواست های خرید',
            },
        ),
    ]
