# Generated by Django 4.2.7 on 2024-01-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_module', '0001_initial'),
        ('buy_and_sell_module', '0010_accept_rejectbuyrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizing_buy_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن خرید توسط')),
                ('finalizing_buy_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن خرید به')),
                ('finalizing_buy_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان نهایی کردن خرید ملک')),
                ('accept_reject_buy_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_reject_buy_request', to='buy_and_sell_module.accept_rejectbuyrequestmodel', verbose_name='درخواست خرید پذیرفته شده/نشده')),
                ('buyed_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن خریداری شده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
            },
        ),
        migrations.CreateModel(
            name='sellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizing_sell_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن فروش توسط')),
                ('finalizing_sell_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='نهایی کردن فروش به')),
                ('finalizing_sell_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان نهایی کردن فروش ملک')),
                ('sell_status', models.BooleanField(default=False, verbose_name='وضعیت فروش')),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='buy_and_sell_module.buymodel', verbose_name='خرید')),
                ('selled_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_token', to='token_module.propertytokenmodel', verbose_name='شماره توکن فروخته شده')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='buyStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در انتظار فروش')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('finalized_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_buy', to='buy_and_sell_module.buymodel', verbose_name='خرید نهایی شده')),
            ],
            options={
                'verbose_name': 'وضعیت خرید',
                'verbose_name_plural': 'وضعیت خریدها',
            },
        ),
    ]
