# Generated by Django 4.2.7 on 2024-01-20 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyDetailesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=50, verbose_name='عنوان ملک')),
                ('property_type', models.CharField(max_length=50, verbose_name='نوع ملک')),
                ('property_length', models.FloatField(default=0.0, verbose_name='متراژ ملک')),
                ('property_price', models.FloatField(default=0.0, verbose_name='قیمت ملک')),
                ('property_short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='تصویر ملک')),
                ('property_document', models.FileField(blank=True, null=True, upload_to='property_documents/', verbose_name='سند ملک')),
                ('property_description', models.TextField(verbose_name='توضیحات کامل')),
                ('property_address', models.TextField(verbose_name='آدرس ملک')),
            ],
            options={
                'verbose_name': 'جزئیات ملک',
                'verbose_name_plural': 'جزئیات ملک ها',
            },
        ),
        migrations.CreateModel(
            name='propertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_owner_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس مالک ملک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ملک تایید شده/تایید نشده')),
                ('token_generated', models.BooleanField(default=False, verbose_name='توکن صادر شده/صادر نشده')),
                ('property_created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد ملک')),
                ('property_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده ملک')),
                ('property_detailes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_detailes', to='property_module.propertydetailesmodel', verbose_name='جزئیات ملک')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'ملک ها',
            },
        ),
        migrations.CreateModel(
            name='propertyStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در حال بررسی')),
                ('accepted', models.BooleanField(default=False, verbose_name='پذیرفتن')),
                ('rejected', models.BooleanField(default=False, verbose_name='رد کردن')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_status', to='property_module.propertymodel', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'وضعیت ملک',
                'verbose_name_plural': 'وضعیت ملک ها',
            },
        ),
    ]
