# Generated by Django 4.2.7 on 2024-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetailesmodel',
            name='property_document',
            field=models.FileField(blank=True, null=True, upload_to='property_documents/', verbose_name='سند ملک'),
        ),
    ]
