# Generated by Django 4.2.7 on 2023-12-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در حال بررسی')),
                ('accepted', models.BooleanField(default=False, verbose_name='پذیرفتن')),
                ('rejected', models.BooleanField(default=False, verbose_name='رد کردن')),
            ],
            options={
                'verbose_name': 'وضعیت ملک',
                'verbose_name_plural': 'وضعیت ملک ها',
            },
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='property_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_status', to='property_module.propertystatusmodel', verbose_name='وضعیت ملک'),
        ),
    ]
