# Generated by Django 4.2.7 on 2023-12-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_module', '0002_propertystatusmodel_propertymodel_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='property_status',
        ),
        migrations.AddField(
            model_name='propertystatusmodel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_status', to='property_module.propertymodel', verbose_name='ملک'),
        ),
    ]
