# Generated by Django 4.2.7 on 2023-12-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blockchainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_name', models.CharField(max_length=250, verbose_name='نام زنجیره بوکی')),
                ('blockchain_address', models.CharField(max_length=500, verbose_name='آدرس سسیستم زنجیره بلوکی')),
                ('blockchain_inventory', models.FloatField(default=0.0, verbose_name='موجودی سیستم زنجیره بلوکی')),
                ('blockchain_transaction_count', models.IntegerField(default=0, verbose_name='تراکنش های انجام شده')),
            ],
            options={
                'verbose_name': 'زنجیره بلوکی',
                'verbose_name_plural': 'زنجیره بلوکی',
            },
        ),
        migrations.CreateModel(
            name='blockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(default=0, verbose_name='شماره بلوک')),
                ('block_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد بلوک')),
                ('mined_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='استخراج شده توسط')),
                ('block_reward', models.FloatField(default=0.0, verbose_name='پاداش بلوک')),
                ('block_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='هش بلوک')),
                ('previous_block_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='هش بلوک قبلی')),
                ('block_nonce', models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره نانس بلوک')),
                ('block_proof_number', models.IntegerField(default=1, verbose_name='شماره اثبات کار بلوک')),
                ('block_merkel_tree_root_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='هش ریشه درخت مرکل بلوک')),
            ],
            options={
                'verbose_name': 'بلاک',
                'verbose_name_plural': 'بلاک ها',
            },
        ),
        migrations.CreateModel(
            name='transactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_from_address', models.CharField(max_length=500, verbose_name='از آدرس')),
                ('transaction_to_address', models.CharField(max_length=500, verbose_name='به آدرس')),
                ('transaction_hash', models.CharField(max_length=500, verbose_name='هش تراکنش')),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد تراکنش')),
                ('transaction_value', models.FloatField(default=0.0, verbose_name='مقدار انتقالی در تراکنش')),
                ('transaction_fee', models.FloatField(default=0.0, verbose_name='هزینه تراکنش')),
                ('transaction_type', models.CharField(max_length=250, verbose_name='نوع تراکنش')),
                ('transaction_nonce', models.IntegerField(default=0, verbose_name='شماره نانس تراکنش')),
                ('transaction_position_in_block', models.IntegerField(default=0, verbose_name='جایگاه تراکنش در بلاک')),
                ('transaction_data', models.TextField(blank=True, null=True, verbose_name='داده های اضافی تراکنش')),
                ('transaction_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_block', to='blockchain_module.blockmodel', verbose_name='بلاک تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='transactionStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True, verbose_name='در صف انتشار')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('not_published', models.BooleanField(default=False, verbose_name='منتشر نشده')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_status', to='blockchain_module.transactionsmodel', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'وضعیت تراکنش',
                'verbose_name_plural': 'وضعیت تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='blockStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده/نشده')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_status', to='blockchain_module.blockmodel', verbose_name='بلوک')),
            ],
            options={
                'verbose_name': 'وضعیت بلاک',
                'verbose_name_plural': 'وضعیت بلاک ها',
            },
        ),
    ]
