# Generated by Django 4.2.7 on 2023-12-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='transactionStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='transactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_from_address', models.CharField(max_length=500, verbose_name='از آدرس')),
                ('transaction_to_address', models.CharField(max_length=500, verbose_name='به آدرس')),
                ('transaction_hash', models.CharField(max_length=500, verbose_name='هش تراکنش')),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد تراکنش')),
                ('transaction_value', models.FloatField(default=0.0, verbose_name='مقدار انتقالی در تراکنش')),
                ('transaction_fee', models.FloatField(default=0.0, verbose_name='هزینه تراکنش')),
                ('transaction_type', models.CharField(max_length=250, verbose_name='نوع تراکنش')),
                ('transaction_nonce', models.IntegerField(default=0, verbose_name='شماره نانس تراکنش')),
                ('transaction_position_in_block', models.IntegerField(default=0, verbose_name='جایگاه تراکنش در بلاک')),
                ('transaction_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_block', to='blockchain_module.blockmodel', verbose_name='بلاک تراکنش')),
                ('transaction_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_status', to='blockchain_module.transactionstatusmodel', verbose_name='وضعیت تراکنش')),
            ],
        ),
    ]
