# Generated by Django 4.2.7 on 2023-12-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionstatusmodel',
            options={'verbose_name': 'وضعیت راکنش', 'verbose_name_plural': 'وضعیت تراکنش ها'},
        ),
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='block_hash',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='هش بلوک'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='block_nonce',
            field=models.IntegerField(default=0, verbose_name='شماره نانس بلوگ'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='block_number',
            field=models.IntegerField(default=0, verbose_name='شماره بلوک'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='block_reward',
            field=models.FloatField(default=0.0, verbose_name='پاداش بلوک'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='block_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد بلوک'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='mined_by',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='استخراج شده توسط'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='previous_block_hash',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='هش بلوک قبلی'),
        ),
        migrations.AddField(
            model_name='transactionstatusmodel',
            name='not_published',
            field=models.BooleanField(default=False, verbose_name='منتشر نشده'),
        ),
        migrations.AddField(
            model_name='transactionstatusmodel',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='در صف انتشار'),
        ),
        migrations.AddField(
            model_name='transactionstatusmodel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='منتشر شده'),
        ),
        migrations.AddField(
            model_name='transactionstatusmodel',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_status', to='blockchain_module.transactionsmodel', verbose_name='تراکنش'),
        ),
        migrations.CreateModel(
            name='blockStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده/نشده')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_status', to='blockchain_module.blockmodel', verbose_name='بلوک')),
            ],
            options={
                'verbose_name': 'وضعیت بلاک',
                'verbose_name_plural': 'وضعیت بلاک ها',
            },
        ),
    ]
