# Generated by Django 4.2.7 on 2024-01-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='merkel_tree_hashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='هش فعلی')),
                ('combined_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='هش ترکیب شده')),
            ],
        ),
    ]
