# Generated by Django 4.2.7 on 2024-01-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0002_merkel_tree_hashes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='merkel_tree_hashes',
            new_name='merkelTreeHashesModel',
        ),
    ]
