# Generated by Django 4.2.7 on 2024-01-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0003_rename_merkel_tree_hashes_merkeltreehashesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merkeltreehashesmodel',
            options={'verbose_name': 'هش درخت مرکل', 'verbose_name_plural': 'هش های درخت مرکل'},
        ),
    ]
