# Generated by Django 4.2.7 on 2023-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0003_alter_blockmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='block_proof_number',
            field=models.IntegerField(default=0, verbose_name='شماره اثبات کار بلوک'),
        ),
    ]
