# Generated by Django 4.2.7 on 2023-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0004_blockmodel_block_proof_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockchainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_name', models.CharField(max_length=250, verbose_name='نام زنجیره بوکی')),
                ('blockchain_address', models.CharField(max_length=500, verbose_name='آدرس سسیستم زنجیره بلوکی')),
                ('blockchain_inventory', models.FloatField(default=0.0, verbose_name='موجودی سیستم زنجیره بلوکی')),
            ],
        ),
    ]
