# Generated by Django 4.2.7 on 2023-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0005_blockchainmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='transaction_data',
            field=models.TextField(blank=True, null=True, verbose_name='داده های اضافی تراکنش'),
        ),
    ]
