# Generated by Django 4.2.7 on 2023-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0006_transactionsmodel_transaction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='block_merkel_tree_root_hash',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='هش ریشه درخت مرکل بلوک'),
        ),
    ]
