# Generated by Django 4.2.7 on 2023-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0007_blockmodel_block_merkel_tree_root_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmodel',
            name='block_nonce',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره نانس بلوگ'),
        ),
    ]
