# Generated by Django 4.2.7 on 2023-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0009_alter_blockmodel_block_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmodel',
            name='block_proof_number',
            field=models.IntegerField(default=1, verbose_name='شماره اثبات کار بلوک'),
        ),
    ]
