# Generated by Django 4.2.7 on 2023-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_module', '0010_alter_blockmodel_block_proof_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainmodel',
            options={'verbose_name': 'زنجیره بلوکی', 'verbose_name_plural': 'زنجیره بلوکی'},
        ),
        migrations.AddField(
            model_name='blockchainmodel',
            name='blockchain_transaction_count',
            field=models.IntegerField(default=0, verbose_name='تراکنش های انجام شده'),
        ),
    ]
