# Generated by Django 4.2.7 on 2024-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletmodel',
            name='inventory',
            field=models.FloatField(default=10000000000.0, verbose_name='موجودی'),
        ),
    ]
