# Generated by Django 4.2.7 on 2024-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_userwalletmodel_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletmodel',
            name='inventory',
            field=models.FloatField(default=0.0, verbose_name='موجودی'),
        ),
    ]
